### ISSUE TITLE
Fraction width namespacing not being interpolated

### ISSUE THREAD

**Issue by euantorano** [inuitcss/trumps.widths#9]
When using variable widths (eg: "inuit-1/2"), the $inuit-namespace variable doesn't seem to be getting interpolated. Below is the output CSS:

``` css
/*------------------------------------*\
    #WIDTHS
\*------------------------------------*/
/**
 * A series of width helper classes that you can use to size things like grid
 * systems. Classes can take a fraction-like format (e.g. `.2/3`) or a spoken-
 * word format (e.g. `two-thirds`). Toggle formats by overriding the
 * `$inuit-use-fractions` variable defined below.
 */
/**
 * Halves.
 */
[class~="#{$inuit-namespace}1/2"], [class~="#{$inuit-namespace}2/4"], [class~="#{$inuit-namespace}3/6"], [class~="#{$inuit-namespace}4/8"], [class~="#{$inuit-namespace}5/10"], [class~="#{$inuit-namespace}6/12"] {
  width: 50% !important; }

/**
 * Thirds.
 */
[class~="#{$inuit-namespace}1/3"], [class~="#{$inuit-namespace}2/6"], [class~="#{$inuit-namespace}3/9"], [class~="#{$inuit-namespace}4/12"] {
  width: 33.33333% !important; }

[class~="#{$inuit-namespace}2/3"], [class~="#{$inuit-namespace}4/6"], [class~="#{$inuit-namespace}6/9"], [class~="#{$inuit-namespace}8/12"] {
  width: 66.66667% !important; }

/**
 * Quarters.
 */
[class~="#{$inuit-namespace}1/4"], [class~="#{$inuit-namespace}2/8"], [class~="#{$inuit-namespace}3/12"] {
  width: 25% !important; }

[class~="#{$inuit-namespace}3/4"], [class~="#{$inuit-namespace}6/8"], [class~="#{$inuit-namespace}9/12"] {
  width: 75% !important; }

/**
 * Fifths.
 */
[class~="#{$inuit-namespace}1/5"], [class~="#{$inuit-namespace}2/10"] {
  width: 20% !important; }

[class~="#{$inuit-namespace}2/5"], [class~="#{$inuit-namespace}4/10"] {
  width: 40% !important; }

[class~="#{$inuit-namespace}3/5"], [class~="#{$inuit-namespace}6/10"] {
  width: 60% !important; }

[class~="#{$inuit-namespace}4/5"], [class~="#{$inuit-namespace}8/10"] {
  width: 80% !important; }

/**
 * Sixths.
 */
[class~="#{$inuit-namespace}1/6"], [class~="#{$inuit-namespace}2/12"] {
  width: 16.66667% !important; }

[class~="#{$inuit-namespace}5/6"], [class~="#{$inuit-namespace}10/12"] {
  width: 83.33333% !important; }

/**
 * Eighths.
 */
[class~="#{$inuit-namespace}1/8"] {
  width: 12.5% !important; }

[class~="#{$inuit-namespace}3/8"] {
  width: 37.5% !important; }

[class~="#{$inuit-namespace}5/8"] {
  width: 62.5% !important; }

[class~="#{$inuit-namespace}7/8"] {
  width: 87.5% !important; }

/**
 * Ninths.
 */
[class~="#{$inuit-namespace}1/9"] {
  width: 11.11111% !important; }

[class~="#{$inuit-namespace}2/9"] {
  width: 22.22222% !important; }

[class~="#{$inuit-namespace}4/9"] {
  width: 44.44444% !important; }

[class~="#{$inuit-namespace}5/9"] {
  width: 55.55556% !important; }

[class~="#{$inuit-namespace}7/9"] {
  width: 77.77778% !important; }

[class~="#{$inuit-namespace}8/9"] {
  width: 88.88889% !important; }

/**
 * Tenths.
 */
[class~="#{$inuit-namespace}1/10"] {
  width: 10% !important; }

[class~="#{$inuit-namespace}3/10"] {
  width: 30% !important; }

[class~="#{$inuit-namespace}7/10"] {
  width: 70% !important; }

[class~="#{$inuit-namespace}9/10"] {
  width: 90% !important; }

/**
 * Twelfths.
 */
[class~="#{$inuit-namespace}1/12"] {
  width: 8.33333% !important; }

[class~="#{$inuit-namespace}5/12"] {
  width: 41.66667% !important; }

[class~="#{$inuit-namespace}7/12"] {
  width: 58.33333% !important; }

[class~="#{$inuit-namespace}11/12"] {
  width: 91.66667% !important; }
```

Building using `gulp-sass 0.7.1` (itself relying on `node-sass 0.8`).
